
title: "TextHive Initiative"
subtitle: "Solving large-scale publishing challenges with Git and Markdown"
url: http://nathanaeljones.com
atom_id: http://nathanaeljones.com

author:
   name: Nathanael Jones
   uri: http://nathanaeljones.com
   email: n@imazen.io
   google_profile: "http://google.com/profiles/104429865496810073908"
   linkedin_profile: "http://www.linkedin.com/in/nathanaeljones"
   twitter_profile: "https://twitter.com/nathanaeljones"
   github_profile: "https://github.com/nathanaeljones"



less: 
  compress: true